title: Santhosh Balaji Portfolio
logo: /assets/img/photo.jpg
description: Proficient in Python and Java, with a strong foundation in Pandas, NumPy, and other data visualization libraries. Desperate about learning new technologies. Eager to contribute to a dynamic team and apply problem-solving skills in a collaborative environment.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
